name: Test

on:
  push:
    paths-ignore:
    - '*.mkd'
    - 'LICENSE'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test_x86:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [nightly, stable, 1.85.0]
        os: [ubuntu-latest, windows-latest, macos-26-intel]
        flags: ["", "--no-default-features", "--release", "--release --no-default-features"]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
            profile: minimal
            default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=Cargo.toml ${{ matrix.flags }} -- --nocapture
  test_aarch64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, windows-11-arm, macOS-latest]
        flags: ["", "--no-default-features", "--release", "--release --no-default-features"]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=Cargo.toml ${{ matrix.flags }} -- --nocapture
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-26-intel, macos-latest, windows-latest, windows-11-arm ]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            default: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench
